export const SET_PEER_CONN = 'SET_PEER_CONN';
export const CLOSE_PEER_CONN = 'CLOSE_PEER_CONN';
export const INITIALIZE_INCOMING_CALL = 'INITIALIZE_INCOMING_CALL';
export const ANSWER_FOR_INCOMING_CALL = 'ANSWER_FOR_INCOMING_CALL';
export const SET_RECIPIENT_NAME = 'SET_RECIPIENT_NAME';
export const SET_LOCAL_STREAM = 'SET_LOCAL_STREAM';
export const SET_MY_VIDEO_SRC = 'SET_MY_VIDEO_SRC';
export const SET_RECIPIENT_VIDEO_SRC = 'SET_RECIPIENT_VIDEO_SRC';